apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: qrpay-self-healing
  namespace: resilience
  labels:
    prometheus: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    - name: payment.rules
      rules:
        - alert: PaymentHighErrorRate
          expr: sum(rate(http_server_requests_seconds_count{service="payment-service",status=~"5.."}[5m]))
              /
              sum(rate(http_server_requests_seconds_count{service="payment-service"}[5m])) > 0.05
          for: 10m
          labels:
            severity: critical
            remediation: payment-quick-restart
          annotations:
            summary: "Payment API returning >5% errors"
            description: |
              The payment service is failing in {{ $labels.namespace }} with an HTTP 5xx ratio above 5%.
              The remediation workflow will automatically restart the deployment.
        - alert: PrimaryRegionOutage
          expr: probe_success{job="ingress-prober", region="primary"} == 0
          for: 3m
          labels:
            severity: critical
            remediation: shift-traffic-to-secondary
          annotations:
            summary: "Primary data center ingress probe failing"
            description: |
              Synthetic checks for the primary data center ingress endpoint are failing.
              Traffic will be rebalanced to the secondary region until the probe recovers.
