apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - otel-collector.yaml
  - service-monitor.yaml
  - instrumentation-configmap.yaml
