apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qrpay-otel-collector
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: monitoring
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: qrpay-otel-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: qrpay-otel-collector
spec:
  selector:
    app.kubernetes.io/name: qrpay-otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 9464
      targetPort: 9464
    - name: monitoring
      port: 8888
      targetPort: 8888
