name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: mbstring, intl, pcntl, sqlite3
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run feature and unit tests
        run: php artisan test --testsuite=Unit --testsuite=Feature

      - name: Run contract tests
        run: composer test:contracts

      - name: Run end-to-end smoke tests
        run: composer test:e2e
