name: Security Scans

on:
  push:
    branches: ["main", "develop"]
  pull_request:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  sast:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          generateSarif: true
      - name: Upload Semgrep report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  dast:
    name: OWASP ZAP Baseline
    runs-on: ubuntu-latest
    needs: sast
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start Laravel server
        run: |
          cp .env.example .env
          php -S 0.0.0.0:8000 -t public >/tmp/php-server.log 2>&1 &
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://127.0.0.1:8000'
          rules_file_name: zap-baseline-rules.tsv
          cmd_options: '-a -d'
      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html
